name = "schulden-kz"
compatibility_date = "2026-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "schulden"
database_name = "schulden"
database_id = "75325642-343e-4093-9124-40c52b91a1d7"
